#!/bin/bash
if [ $# != 1 ]
then
    awk -f ./catiplist IPLIST loadiprank=$1 
    exit 1;
fi

if  echo $1 | grep -q '^[1-9]\+$'
then
    ip=`awk -f catiplist IPLIST loadiprank=$1 | cut -d " " -f 1`
    user=`awk -f catiplist IPLIST loadiprank=$1 | cut -d " " -f 2`
    passwd=`awk -f catiplist IPLIST loadiprank=$1 | cut -d " " -f 3`
    ssh "${user}"@"${ip}"
else
    awk -f catiplist IPLIST loadiprank=$1 
    exit 0;
fi
